/*
 * Filters.h
 *
 *  Created on: 01/05/2017
 *      Author: root
 */

#ifndef FILTERS_H_
#define FILTERS_H_

#include <linux/filter.h>

namespace Packet{
namespace Filters{

struct sock_filter beacon_filter_code[] = {		//Beacon filter	generated by bpf_asm. It checks whether the 4 more significant bytes at offset 0x1A are 8
		{ 0x30,  0,  0, 0x00000002 },
		{ 0x07,  0,  0, 0000000000 },
		{ 0x30,  0,  0, 0x00000003 },
		{ 0x64,  0,  0, 0x00000008 },
		{ 0x0c,  0,  0, 0000000000 },
		{ 0x50,  0,  0, 0000000000 },
		{ 0x74,  0,  0, 0x00000002 },
		{ 0x54,  0,  0, 0x00000003 },
		{ 0x15,  0,  4, 0000000000 },
		{ 0x50,  0,  0, 0000000000 },
		{ 0x74,  0,  0, 0x00000004 },
		{ 0x15,  0,  1, 0x00000008 },
		{ 0x06,  0,  0, 0xffffffff },
		{ 0x06,  0,  0, 0000000000 },
};

struct sock_filter probe_filter_code[] = {		//Beacon filter	generated by bpf_asm. It checks whether the 4 more significant bytes at offset 0x1A are 8
		{ 0x30,  0,  0, 0x00000002 },
				{ 0x07,  0,  0, 0000000000 },
				{ 0x30,  0,  0, 0x00000003 },
				{ 0x64,  0,  0, 0x00000008 },
				{ 0x0c,  0,  0, 0000000000 },
				{ 0x50,  0,  0, 0000000000 },
				{ 0x74,  0,  0, 0x00000002 },
				{ 0x54,  0,  0, 0x00000003 },
				{ 0x15,  0,  4, 0000000000 },
				{ 0x50,  0,  0, 0000000000 },
				{ 0x74,  0,  0, 0x00000004 },
				{ 0x15,  0,  1, 0x00000008 },
				{ 0x06,  0,  0, 0xffffffff },
				{ 0x06,  0,  0, 0000000000 },
};

struct sock_filter handshake_filter_code[] = {		//Handshake filter	generated by bpf_asm. It checks whether the 4 more significant bytes at offset 0x1A are 8
		{ 0x30,  0,  0, 0x00000002 },
		{ 0x07,  0,  0, 0000000000 },
		{ 0x30,  0,  0, 0x00000003 },
		{ 0x64,  0,  0, 0x00000008 },
		{ 0x0c,  0,  0, 0000000000 },
		{ 0x50,  0,  0, 0000000000 },
		{ 0x74,  0,  0, 0x00000002 },
		{ 0x54,  0,  0, 0x00000003 },
		{ 0x15,  0, 10, 0x00000002 },
		{ 0x50,  0,  0, 0000000000 },
		{ 0x74,  0,  0, 0x00000004 },
		{ 0x15,  0,  7, 0x00000008 },
		{ 0x50,  0,  0, 0x00000001 },
		{ 0x74,  0,  0, 0x00000006 },
		{ 0x54,  0,  0, 0x00000001 },
		{ 0x15,  0,  3, 0000000000 },
		{ 0x48,  0,  0, 0x00000020 },
		{ 0x15,  0,  1, 0x0000888e },
		{ 0x06,  0,  0, 0xffffffff },
		{ 0x06,  0,  0, 0000000000 },
};



}
}



#endif /* FILTERS_H_ */
